name: CI tests
on:
  - push
jobs:
  run-unittest:
    runs-on: ubuntu-22.04
    container: python:3.10
    strategy:
      matrix:
        kc_version: [9.0.3, 15.0.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # install dependencies from setup.py
      - run: pip install .
      - name: Wait on keycloak to be up
        run: curl -k --connect-timeout 60 --retry 60 --retry-delay 1 --retry-connrefused --retry-max-time 60 https://keycloak:8443 -v
      - run: python -m unittest
    env:
      KEYCLOAK_API_CA_BUNDLE:
      KC_ENDPOINT: https://keycloak:8443/
      KC_USER: admin
      KC_PASSWORD: admin
      KC_REALM: ci-test-realm
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:${{ matrix.kc_version }}
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin

  # Install package, the check it can be imported
  test-import:
    runs-on: ubuntu-22.04
    container: python:3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # install dependencies from setup.py
      - run: pip install .
      - run: python -c 'from kcapi import OpenID; print(OpenID);'
      - run: python -c 'from kcapi.rest.groups import Groups; print(Groups);'
      # Do this also from some arbitrary directory
      - run: cd /var/tmp && python -c 'from kcapi import OpenID; print(OpenID);'
      - run: cd /var/tmp && python -c 'from kcapi.rest.groups import Groups; print(Groups);'

  # build whl and upload to pypi.org
  build_whl:
    if: github.ref_type == 'tag'
    needs:
      - run-unittest
      - test-import
    runs-on: ubuntu-22.04
    container: python:3.10
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TWINE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo ref_name=${{ github.ref_name }}
      - run: pip install -r requirements-dev.txt
      - run: python -m build
      # - run: python3 -m twine upload --repository testpypi dist/*
      - run: python3 -m twine upload dist/*
